# Generated by Django 5.1.4 on 2025-01-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id_especie', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cientifico', models.CharField(max_length=255)),
                ('nome_comum', models.CharField(max_length=255)),
                ('habitat', models.CharField(choices=[('N', 'Norte'), ('NE', 'Nordeste'), ('S', 'Sul'), ('SE', 'Sudeste'), ('CO', 'Centro-Oeste')], max_length=2)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='especies')),
            ],
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id_artigo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='artigos')),
                ('data_publicacao', models.DateField()),
                ('autor', models.CharField(max_length=255)),
                ('especies', models.ManyToManyField(related_name='artigos', to='main.especie')),
            ],
        ),
    ]
